"""Initial migration

Revision ID: 69c91cb818c5
Revises: 
Create Date: 2022-11-04 12:40:48.680999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69c91cb818c5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('info', sa.VARCHAR(length=50), nullable=False),
    sa.Column('category', sa.VARCHAR(length=20), nullable=False),
    sa.Column('date_added', sa.DATETIME(), nullable=False),
    sa.Column('done', sa.BOOLEAN(), nullable=True),
    sa.Column('poster_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['poster_id'], ['lists.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###
